#include <iostream>
using namespace std;

void generateBinaryStrings(int n, string str) {
	// The base case: when n reaches 0, the string of length n if completely formed
	if (n < 1) {
		cout << str << endl;
		return;
	}
	// Each binary string of length n is generated by letting '0' or '1' precede the binary strings of length n - 1
	// We use 2 recursive calls for two cases : adding '0' and '1' to the back of the n-1 length strings
	generateBinaryStrings(n - 1, str + "0");
	generateBinaryStrings(n - 1, str + "1");
}

int main() {
	int n;
	cin >> n;
	// Start the recursive function by passing the empty string
	generateBinaryStrings(n, "");
}